kind: pipeline
name: pipeline

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: pingu/drone-plugin-kontena
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args: ["--no-cache"]
  when:
    status: [ success ]
    branch: [ master ]
