pipeline:
  publish:
    image: plugins/docker
    repo: pingu/drone-plugin-kontena
    tags: latest
    secrets: [ docker_username, docker_password ]
    build_args: ["--no-cache"]
    when:
      status: [ success ]
      branch: [ master ]
